# Generated by Django 4.1.1 on 2022-10-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Single article (change in model.py)', 'verbose_name_plural': 'Many articles (change in model.py)'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Single comment (change in model.py)', 'verbose_name_plural': 'Many comments (change in model.py)'},
        ),
    ]
